name: JAVA CI

env:
  WORKER_DIR: java

on:
  push:
    branches: [master, dev]
    paths:
      - 'java/**'
  pull_request:
    branches: [master, dev]
    paths:
      - 'java/**'

defaults:
  run:
    working-directory: java

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: ${{ env.WORKER_DIR }}

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: ${{ env.WORKER_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.PKG_DEPLOY_TOKEN }}
